### ISSUE TITLE
Incorrect links to conferences

### ISSUE THREAD

**Issue by cdtinney** [tatianamac/TM11#2]
Some links on the homepage are incorrect:

- CSSCamp directs to `https://www.clarityconf.com/`
- PerfNow() directs to `https://www.clarityconf.com/`
- A11YTO directs to `https://jointfuturesconf.com/`

**Comment by tatianamac** [comment]
Thank you for flagging it! Should be fixed now. That was a mess! 😅

**Comment by tatianamac** [comment]
Thank you for flagging it! Should be fixed now. That was a mess! 😅
